### ISSUE TITLE
Downloading an zipped HTML report

### ISSUE THREAD

**Issue by fjc15** [paragbaxi/qualysapi#83]
I'm trying to pull down a report that is a .zip binary  - which is how Qualys present their HTML format reports. I'm having problems getting the results written to disk in a way that I can use unzip on it.

If I try the following:

```
from PIL import Image
from io import BytesIO

results = qgc.request(call, parameters)
z = Image.open(BytesIO(results.content))

```

I get the error 
`AttributeError: 'str' object has no attribute 'content'`

**Comment by megavis** [comment]
Hi @fjc15 I've just solved similar problem (but previously had been beating about it thorough two hours :))
That behavior appear because author return only the value **text** of object **response** in his code:
**connector.py**
 _QGConnector->request_
```
                 ...
                 # Likely an asset search api_call.
                 logger.debug(e)
                 pass
             # Response received.
             response = request.text
             logger.debug("response text =\n%s", response)
             # Keep track of how many retries.
             retries += 1
             # Check for concurrent scans limit.
             ...
```
I encountered that issue when had been tried to write downloaded pdf in a binary file.
Hope, it helps.
